services:
  database:
    container_name: oracle19c
    image: oracle/database:19.3.0-ee
    environment:
      ORACLE_PASSWORD: system
    ports:
      - '1521:1521'
    healthcheck:
      test: ["CMD", "true"]