#Database connection configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PSQLDEVBR
    username: hub
    password: forumhub
    driver:
      class: org.postgresql.Driver

  #Show formated SQL statements
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  #Override duplicated beans encountered in the repositories
  main:
    allow-bean-definition-overriding: true

  #Authorization server configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8082

#Registered topichub and userhub client credentials
registered:
  client:
    topic:
      name: forumhub-topic
      client-id: hub-topic
      password: topic123456
    user:
      name: forumhub-user
      client-id: hub-user
      password: user123456

#Auth-Server port
server:
  port: 8082

logging:
  level:
    org:
      springframework:
        security: trace
