#Database connection configuration
spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver:
      class: org.postgresql.Driver

  #Show formated SQL statements
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  #Override duplicated beans encountered in the repositories
  main:
    allow-bean-definition-overriding: true

  #Authorization server configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8082

#Auth-Server port
server:
   port: 8082

logging:
  level:
    org:
      springframework:
        security: trace
